use_frameworks!

platform :ios, '9.0'

target 'SFTool_Example' do
  pod 'SFTool', :path => '../'

  target 'SFTool_Tests' do
    inherit! :search_paths

    #pod 'FBSnapshotTestCase'
  end
  
  pod 'SFCategory', :git => 'https://github.com/jack110530/SFCategory.git', :branch => 'master'
  pod 'SFMacro', :git => 'https://github.com/jack110530/SFMacro.git', :branch => 'master'
  
end
